### ISSUE TITLE
Rf -fold does not work with RNA structure 

### ISSUE THREAD

**Issue by Frappadoo** [dincarnato/RNAFramework#38]
Hi Danny Incarnato,

I have set up RNAframework on my computer and was testing the SHAPE-MaP workflow on here https://rnaframework-docs.readthedocs.io/en/latest/cases/ The ViennaRNA method works amazingly well, however whenere I try to use the RNAstructure method, I get the following error.

rf-fold -m 2 -g -md 500 -w -pk -km 2 -ko 100 -pw 1600 -po 375 -wt 300 -fw 3000 -fo 300 HIV_norm/ -ow

[+] Checking method's requirements...
[+] Making output directory tree...
[+] Importing XML file(s) [1 imported]
[+] Folding RNA structures [Last: none]
Thread 1 terminated abnormally: Can't use string (" 2900  ENERGY = -1196.6  HIV_0-2"...) as an ARRAY ref while "strict refs" in use at /Users/francescappadoo/Desktop/RNAFramework/rf-fold line 858.

[+] Folding statistics:

  [*] Folded transcripts:    0
  [*] Discarded transcripts: 1 total
                             0 XML parsing failed
                             0 constraint file generation failed
                             0 FASTA file generation failed
                             0 folding failed
                             1 I/O error
                             0 pseudoknotted folding failed

[+] All done.

Do you have any suggestions for this?

Thank you for your help,

Fran

**Comment by dincarnato** [comment]
Hi Fran,

Thanks for reporting.
I will look into this and get back to you. I suspect this might be a bug introduced in the last release.

Danny

**Comment by dincarnato** [comment]
Did you git pull the very last version?

**Comment by Frappadoo** [comment]
Hi Danny,

Yes it's version 2.8.3. I ran it with the same conditions that were in the link I previously sent

**Comment by dincarnato** [comment]
Fixed. Please issue a git pull and try!

**Comment by Frappadoo** [comment]
Hi,

I have git pulled it and tried it but d I am getting this error still

rf-fold -m 2 -g -md 500 -w -pk -km 2 -ko 100 -pw 1600 -po 375 -wt 300 -fw 3000 -fo 300 HIV_norm/ -ow

[+] Checking method's requirements...
[+] Making output directory tree...
[+] Importing XML file(s) [1 imported]
[+] Folding RNA structures [Last: none]Thread 1 terminated abnormally: Can't use string (" 2900  ENERGY = -1156.4  HIV_0-2"...) as an ARRAY ref while "strict refs" in use at /Users/francescappadoo/Desktop/RNAFramework/rf-fold line 858.

[+] Folding statistics:

  [*] Folded transcripts:    0
  [*] Discarded transcripts: 1 total
                             0 XML parsing failed
                             0 constraint file generation failed
                             0 FASTA file generation failed
                             0 folding failed
                             1 I/O error
                             0 pseudoknotted folding failed

[+] All done.

**Comment by Frappadoo** [comment]
Hi Danny, 

It works now thank you! I had a second copy of RNAframework in my path.

**Comment by wangguiqian** [comment]
(work) [yqming@sg56 PEDV]$ ~/Software/RNAFramework/rf-fold -m 1 -g -md 500 -w -pk -km 2 -ko 100 -pw 1600 -po 375 -wt 300 -fw 3000 -fo 300 rf-norm/FSE.xml 

[+] Checking method's requirements...
[+] Making output directory tree...
[+] Importing XML file(s) [1 imported]                                                                                                               
[+] Folding RNA structures [Last: none]
[+] Folding statistics:

  [*] Folded transcripts:    0
  [*] Discarded transcripts: 1 total
                             0 XML parsing failed
                             0 constraint file generation failed
                             0 FASTA file generation failed
                             0 folding failed
                             0 I/O error
                             1 pseudoknotted folding failed

[+] All done.

But I using the command to ran ,i get the errors .
Could you tell me what happen? 
@Frappadoo @kenibrewer
